#!/bin/bash
counter=$1
while [ $counter -gt 0 ]
do
  cp testcall.bak testcall.call
  chmod 777 testcall.call
  mv testcall.call /var/spool/
  asterisk/outgoing
  counter=$(( $counter - 1 ))
done

[testing]
  exten => s,1,Answer
  exten => s,2,Playback(/var/lib
  /asterisk/sounds/tt-weasels)
  exten => s,3,Hangup
